[package]
name = "remda"
version = "0.1.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
log = "0.4"
